// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.browser.newtabpage.activity-stream.discoverystream.enabled", true);
user_pref("app.normandy.user_id", "1dbacf4e-708e-416e-866d-7dc239ed93d5");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1571625925);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 2516);
user_pref("browser.cache.disk.capacity", 399360);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1571625899);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 86);
user_pref("browser.newtabpage.activity-stream.impressionId", "{9658c77b-22b7-41ed-8795-b8781c5bc24e}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1571625930592");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1571627717592");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1571625911165");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1571629511165");
user_pref("browser.search.region", "US");
user_pref("browser.slowStartup.averageTime", 14047);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20191002193559");
user_pref("browser.startup.homepage_override.mstone", "69.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1571625901);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1571625909776");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "69.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "ae660b9bc19e40aa9af24b1a90d75e7d");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "69.0.2");
user_pref("extensions.lastPlatformVersion", "69.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"4caa6645-e604-4d89-88a3-27683ee94d8a\",\"fxmonitor@mozilla.org\":\"6e14d705-27bb-4697-aaf7-76664f1fbd7d\",\"screenshots@mozilla.org\":\"3faf4451-9075-4f4a-8eb0-6c9129905406\",\"webcompat-reporter@mozilla.org\":\"6eb69e36-fef6-4253-bebf-8b7f111e6791\",\"webcompat@mozilla.org\":\"678a665e-f136-4642-b768-1d006562ad0d\",\"default-theme@mozilla.org\":\"bd96b4b0-d3f2-4f56-8cf5-40a33a02522a\",\"google@search.mozilla.org\":\"c0d9bc82-aea7-43b4-b16f-dee0556027d0\",\"amazondotcom@search.mozilla.org\":\"e77ff929-87d8-42c9-ac4d-71ad6ab7e45f\",\"bing@search.mozilla.org\":\"2e143ad9-9074-40a1-8811-24098cd833e6\",\"ddg@search.mozilla.org\":\"3cfe12b4-5f91-45ca-adf1-229ccce9bf57\",\"ebay@search.mozilla.org\":\"e05ecfd9-9174-4964-afb2-a9b16a42a298\",\"twitter@search.mozilla.org\":\"834c8710-17d1-4f60-87b7-1f5966c5e1de\",\"wikipedia@search.mozilla.org\":\"bc18d1d5-bc13-40db-9513-0e7f36efa81e\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "1b8bf293-085b-43ec-9491-6455fe53f92d");
user_pref("security.sandbox.plugin.tempDirSuffix", "7285f4a0-7638-43b7-8ac7-7932e5c3a623");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1571625887);
user_pref("toolkit.telemetry.cachedClientID", "cb4afffa-d334-4938-b45e-64a345e0551e");
user_pref("toolkit.telemetry.previousBuildID", "20191002193559");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "control");
